Repository arduino/Arduino, pull requests merged in 2018-08, with the labels that each got.

#7674 Fixed the bug that doesn't updates the title when an example sketch is saved
  app/src/processing/app/Editor.java
  app/src/processing/app/SketchController.java
Labels: Component: IDE user interface

#7888 Fix "Increase Font Size" keybindings
  app/src/processing/app/Editor.java
Labels: Component: IDE user interface, Type: Bug, Type: Improvement

#7957 Java now requires MacOSX 10.8 Mountain Lion or later
  build/build.xml
Labels: OS: OSX
