Repository arduino/Arduino, pull requests merged in 2019-04, with the labels that each got.

#8638 Preferences: arrange checkboxes into two columns
  app/src/cc/arduino/view/preferences/Preferences.java
Labels: Component: IDE user interface

#8781 Linux build: remove symlinks only if they exist
  build/linux/dist/install.sh
Labels: OS: Linux

#8682 Replace "unzip/tar" in build.xml by Ant's provided unzip/untar method
  build/build.xml
Labels: feature request
