Repository arduino/Arduino, pull requests merged in 2020-02, with the labels that each got.

#9698 Treat JUnit errors as failures to increase visibility
  app/build.xml
Labels: Type: Improvement

#9696 Build Arduino IDE and run tests on GitHub-hosted runners
  .github/workflows/ant.yml
Labels: Type: Improvement

#9695 Update CommandLineTest.testCommandLineVersion()
  app/src/processing/app/Base.java
Labels: Type: Bug

#9748 Fix libraries comparator logic in library manager
  app/src/cc/arduino/contributions/libraries/ui/ContributedLibraryReleasesComparator.java
Labels: Component: Board/Lib Manager, Type: Bug
